### ISSUE TITLE
Find pop up cannot be moved (but this overlaps with another problem)

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#11]
Initially I opened this to note that I could not move the find pop-up window when I tried. But when I tried to recreate the problem, no pop up was generated at all. I tried twice in Brave Browser (based on Chrome) and in Safari. I am working on a new Macbook Air.

A follow up video: I did manage to get the windows popping up again. It required going into Search for Coin Finds and searching by custom region. Is this expected behaviour? I would have assumed we would want pop ups to come up with Find Focus find spots, as well. I will note, coming full circle, that I could still not MOVE this pop up window.

https://user-images.githubusercontent.com/28210739/117478882-f0460d80-af1c-11eb-8638-73bdcb24973c.mov

https://user-images.githubusercontent.com/28210739/117478904-f63bee80-af1c-11eb-90fb-079ecdb9b074.mov

**Comment by leemordechai** [comment]
Turns out this was related to a major issue that caused FLAME to break on certain computers (e.g. my laptop but not my desktop). The underlying reason was a change in ESRI's code. The absence of popups was temporary as the developer looked for a fix; the current fix is to disable moving some of the popups which apparently solves the problem. Not ideal but better than having FLAME unusable by some for now.

Discussed with the developer possibilities to have a better solution post-launch

**Comment by pyzmark** [comment]
Did we solve this problem? If so, should we close this issue?
