### ISSUE TITLE
Mints with strange georeference numbers

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#39]
I am not sure what is going on here, but the numbers for the first couple of mints look strange. There is an extra zero BEFORE the first two numbers. Is this doing anything to functionally interfere with these mints? I don't know. 

All of these seem to share the fact that they lack much in the way of information so there is no way to check without going to the coin find itself (we need to provide more intuitive ways of checking references for mint results...). These mints need to be re-entered in a more descriptive way, but that is besides the point.

The main question is, why the strange numbers?

![image](https://user-images.githubusercontent.com/28210739/164024557-b40193eb-69a3-4fb1-87ca-9aab4fdb3602.png)

**Comment by leemordechai** [comment]
@pyzmark Not sure this is that much of a problem, I'm assuming the first zeros were inputted manually - by @IliaCurtoPelle I think since they're all in Persia/Central Asia. The Nishapur mint a few rows down your screenshot has the same issue.

On the positive side, the mints appear where they're supposed to be located - you can search for them in the app. However, there have been some issues with the mint attributions. The most serious error is in the image below - a vague mint in Persia that is associated with many finds in Italy doesn't seem right. 

![image](https://user-images.githubusercontent.com/16713928/164041795-13a91d7f-8cd1-492e-8fee-1dfd6c02dd08.png)

**Comment by pyzmark** [comment]
I checked. It's Merle, not Ilia. When you open to edit there is no fore-fronted zero. But you're right, it might not functionally matter. The big problem, as you also note, is mint attribution, since what is there now is wholly mysterious. There should be some way of tying it to at least some speculative mint, one of our own SNS-based attributions (with an entry in our Sasanian mint document), or something.

**Comment by pyzmark** [comment]
@IliaCurtoPelle Can you look at this, determine what these mints are, and see what might work best for re-labelling them?

**Comment by leemordechai** [comment]
@pyzmark @IliaCurtoPelle - reminder about this

**Comment by leemordechai** [comment]
@pyzmark @IliaCurtoPelle another reminder here

**Comment by ilia-curtopelle** [comment]
These seem to all be uncertain coins which are in no way Sassanian. Once we fix Sassanian minting, I can check for any Sassanian coins in there. Otherwise, we should jsut mark them as "Unknown"

**Comment by leemordechai** [comment]
Checked with Pavle and the issue was visual only; it's now fixed so closing the comment.
