### ISSUE TITLE
Unused denominations - they persist

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#8]
Some legacy denominations seem to still be in the system. No entries are returned when filtering data for "1/3 dinar" and "1/6 dinar" under the Advanced Search, "Search for coin finds". We should remove these. Should this thread be a place to aggregate such denominations as they come up? It can be periodically reopened, as the issue pops back up.

** a secondary question might be, can we automate the trimming of denominations when no examples exist anymore? Or can they be rendered invisible in the denomination-selector on the map tool?

**Comment by leemordechai** [comment]
If I understand correctly these denominations appear in the literature (e.g. in Phase I) - we simply haven't cataloged any coins that belong to them. This is different from the overlapping denominations (e.g. 1/3 solidus and tremissis) where one of the pair should be removed - let me know if you think otherwise!

**Comment by leemordechai** [comment]
Will close this for now - please re-open if necessary!
